version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'tskpong'
      POSTGRES_PASSWORD: 'tskpong'
      POSTGRES_DB: 'tskpong'   
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "tskpong", "-U", "tskpong"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres_volumes:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c " chmod +x ./docker_entrypoint.sh && ./docker_entrypoint.sh"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      db: 
        condition: service_healthy

volumes:
  postgres_volumes:
