# Generated by Django 5.0.3 on 2024-04-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_gamers_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamers',
            name='profile_picture',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
