# Generated by Django 5.0.3 on 2024-04-23 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='profile_picture',
            field=models.CharField(default=datetime.datetime(2024, 4, 23, 13, 51, 57, 819093, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
