# Generated by Django 5.0.3 on 2024-04-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
