# Generated by Django 5.0.3 on 2024-04-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_friends_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocklist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('blocker', models.CharField(max_length=100)),
                ('blocked', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='friends',
            name='status',
        ),
    ]
