# Generated by Django 5.0.3 on 2024-04-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_blocklist_remove_friends_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('winner', models.CharField(max_length=100)),
                ('loser', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
