# Generated by Django 5.0.3 on 2024-04-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_gamehistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamehistory',
            old_name='loser',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='gamehistory',
            old_name='type',
            new_name='user1',
        ),
        migrations.RenameField(
            model_name='gamehistory',
            old_name='winner',
            new_name='user1score',
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='user2',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='user2score',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
