# Generated by Django 5.0.3 on 2024-04-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='players',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
