# Generated by Django 5.0.3 on 2024-04-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_tournament_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='score',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
