# Generated by Django 5.0.3 on 2024-04-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_notifications_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rps',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user1', models.CharField(max_length=100)),
                ('user2', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
