# Generated by Django 5.0.3 on 2024-04-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_rps'),
    ]

    operations = [
        migrations.AddField(
            model_name='rps',
            name='user1_attack',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rps',
            name='user2_attack',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
