# Generated by Django 5.0.3 on 2024-05-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_rps_user1_attack_rps_user2_attack'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamers',
            name='date',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
